// Travio/Frontend/src/components/Navbar.jsx
import { Link, NavLink, useLocation } from 'react-router-dom'
import { useState, useEffect } from 'react'

export default function Navbar() {
  const location = useLocation();
  const [isVisible, setIsVisible] = useState(true);
  const [lastScrollY, setLastScrollY] = useState(0);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const isLightNavbar = location.pathname.startsWith('/blog');

  useEffect(() => {
    const handleScroll = () => {
      const currentScrollY = window.scrollY;
      
      if (currentScrollY < lastScrollY || currentScrollY < 10) {
        // Scrolling up or at top
        setIsVisible(true);
      } else {
        // Scrolling down
        setIsVisible(false);
      }
      
      setLastScrollY(currentScrollY);
    };

    window.addEventListener('scroll', handleScroll, { passive: true });

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, [lastScrollY]);

  const toggleMobileMenu = () => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  };

  const closeMobileMenu = () => {
    setIsMobileMenuOpen(false);
  };

  const desktopLinkClass = ({ isActive }) => {
    if (isLightNavbar) {
      return `${isActive ? 'text-[#7FB62A]' : 'text-gray-900'} hover:text-[#7FB62A] transition duration-200 font-medium text-sm lg:text-base`;
    }

    return `${isActive ? 'text-[#A8DF34]' : 'text-white'} hover:text-[#A8DF34] transition duration-200 font-medium drop-shadow-lg text-sm lg:text-base`;
  };

  const mobileLinkClass = ({ isActive }) => {
    if (isLightNavbar) {
      return `block ${isActive ? 'text-[#7FB62A]' : 'text-gray-900'} hover:text-[#7FB62A] transition duration-200 font-medium py-2 border-b border-gray-300`;
    }

    return `block ${isActive ? 'text-[#A8DF34]' : 'text-white'} hover:text-[#A8DF34] transition duration-200 font-medium drop-shadow-lg py-2 border-b border-white border-opacity-20`;
  };

  return (
    <nav className={`w-full fixed top-0 z-50 transition-all duration-300 ${
      isVisible ? 'translate-y-0' : '-translate-y-full'
    } ${isLightNavbar ? 'bg-white/95 border-b border-gray-200 shadow-sm' : 'bg-transparent backdrop-blur-sm'}`}>
      <div className="w-full px-4 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between">
          {/* Logo */}
          <div className="flex-shrink-0">
            <Link to="/" className="block">
              <div className="h-10 w-32 flex items-center justify-center overflow-hidden">
                <img
                  src="/bahan/Logo2.png"
                  alt="Logo"
                  className="h-14 w-auto transition-transform duration-300 ease-out hover:scale-125"
                />
              </div>
            </Link>
          </div>


          {/* Hamburger Menu Button - Mobile Only */}
          <button
            onClick={toggleMobileMenu}
            className="md:hidden flex flex-col gap-0.5 cursor-pointer bg-transparent p-1"
          >
            <span className={`w-4 h-0.5 ${isLightNavbar ? 'bg-gray-900' : 'bg-white'} transition-all duration-300 ${isMobileMenuOpen ? 'rotate-45 translate-y-1' : ''}`}></span>
            <span className={`w-4 h-0.5 ${isLightNavbar ? 'bg-gray-900' : 'bg-white'} transition-all duration-300 ${isMobileMenuOpen ? 'opacity-0' : ''}`}></span>
            <span className={`w-4 h-0.5 ${isLightNavbar ? 'bg-gray-900' : 'bg-white'} transition-all duration-300 ${isMobileMenuOpen ? '-rotate-45 -translate-y-1' : ''}`}></span>
          </button>

          {/* Desktop Navigation Links */}
          <div className="hidden md:flex flex-1 justify-center gap-4 lg:gap-8 ml-8">
            <NavLink to="/" className={desktopLinkClass}>
              Home
            </NavLink>
            <NavLink to="/marketers" className={desktopLinkClass}>
              Marketers
            </NavLink>
            <NavLink to="/media-owner" className={desktopLinkClass}>
              Media Owner
            </NavLink>
            <NavLink to="/industri" className={desktopLinkClass}>
              Industri
            </NavLink>
            <NavLink to="/pricing" className={desktopLinkClass}>
              Pricing
            </NavLink>
            <NavLink to="/blog" className={desktopLinkClass}>
              Blog
            </NavLink>
          </div>

          {/* Desktop Call Us Button */}
          <div className="hidden md:flex flex-shrink-0">
            <button className="bg-[#A8DF34] text-black px-4 lg:px-6 py-2 rounded-lg hover:text-white transition duration-200 font-semibold text-sm lg:text-base">
              Call Us
            </button>
          </div>
        </div>

        {/* Mobile Menu */}
        {isMobileMenuOpen && (
          <div className={`md:hidden mt-4 pb-4 space-y-3 animate-in fade-in duration-300 ${isLightNavbar ? 'bg-white rounded-lg px-3 pt-2 border border-gray-200' : ''}`}>
            <NavLink
              to="/"
              onClick={closeMobileMenu}
              className={mobileLinkClass}
            >
              Home
            </NavLink>
            <NavLink
              to="/marketers"
              onClick={closeMobileMenu}
              className={mobileLinkClass}
            >
              Marketers
            </NavLink>
            <NavLink
              to="/media-owner"
              onClick={closeMobileMenu}
              className={mobileLinkClass}
            >
              Media Owner
            </NavLink>
            <NavLink
              to="/industri"
              onClick={closeMobileMenu}
              className={mobileLinkClass}
            >
              Industri
            </NavLink>
            <NavLink
              to="/pricing"
              onClick={closeMobileMenu}
              className={mobileLinkClass}
            >
              Pricing
            </NavLink>
            <NavLink
              to="/blog"
              onClick={closeMobileMenu}
              className={mobileLinkClass}
            >
              Blog
            </NavLink>
            <button className="w-full bg-[#A8DF34] text-black px-4 py-2 rounded-lg transition duration-200 font-semibold mt-3">
              Call Us
            </button>
          </div>
        )}
      </div>
    </nav>
  );
}

// vue-project/src/components/Navbar.vue
<template>
  <transition name="navbar-fade">
    <header
      v-show="showHeader"
      class="bg-orange-500/90 text-white fixed top-0 left-0 w-full z-50 transition-all duration-300"
      :class="{ 'backdrop-blur-md': true }"
    >
      <div class="container mx-auto px-4 py-4 flex items-center justify-between">
        <div class="flex items-center">
          <img src="/image/suitmedia1.png" alt="Suitmedia Logo" class="h-8 w-auto" />
        </div>
        <nav class="hidden md:flex space-x-8">
          <a
            v-for="item in menu"
            :key="item.name"
            :href="item.href"
            class="hover:text-orange-200 transition-colors"
            :class="isActive(item.href) ? 'underline underline-offset-4 font-semibold' : ''"
          >
            {{ item.name }}
          </a>
        </nav>
      </div>
    </header>
  </transition>
</template>
<script setup>
import { ref, onMounted, onUnmounted } from 'vue'

// Menu items
const menu = [
    { name: 'Work', href: '/work' },
    { name: 'About', href: '/about' },
    { name: 'Services', href: '/services' },
    { name: 'Ideas', href: '/ideas' },
    { name: 'Careers', href: '/careers' },
    { name: 'Contact', href: '/contact' }
]

// Show/hide header on scroll
const showHeader = ref(true)
let lastScrollY = window.scrollY

const handleScroll = () => {
    const currentScrollY = window.scrollY
    if (currentScrollY < 10) {
        showHeader.value = true
    } else if (currentScrollY > lastScrollY) {
        // Scrolling down
        showHeader.value = false
    } else {
        // Scrolling up
        showHeader.value = true
    }
    lastScrollY = currentScrollY
}

onMounted(() => {
    window.addEventListener('scroll', handleScroll)
})
onUnmounted(() => {
    window.removeEventListener('scroll', handleScroll)
})

// Active state based on current location
function isActive(href) {
    // For demo, use window.location.pathname
    // In real app with vue-router, use useRoute()
    return window.location.pathname === href
}
</script>
<style scoped>
.navbar-fade-enter-active,
.navbar-fade-leave-active {
  transition: opacity 0.3s;
}
.navbar-fade-enter-from,
.navbar-fade-leave-to {
  opacity: 0;
}
</style>
